### ISSUE TITLE
Two fields get filled up for providing input in one field

### ISSUE THREAD

**Issue by Nazarah** [apinf/open-api-designer#106] opened 2017-05-23 11:35 UTC
# Reproduction
* Go to http://apinf.org/open-api-designer
*  In Header section, add value in **Name** field under **Contact**.
* Look at preview window

# Result
* preview window shows **Name** field under **License** gets filled up with the input given for **Name** field under **Contact**.
* In Editor, no value appears in **Name** field under **Contact**.
![openapi preview](https://cloud.githubusercontent.com/assets/17976243/26352564/ff7f6b0a-3fc4-11e7-8aee-840254fd480e.gif)

# System
* Windows 8
* Chrome

**Comment by tulir** [comment] 2017-05-23 12:16
Duplicate of #77. This has been fixed in `master`, but has not yet been merged into `gh-pages`. See https://oai.maunium.net/master/ for a hosted version of the master branch.

**Closed by tulir** 2017-05-23 12:16 UTC
Labels: bug

**Comment by Nazarah** [comment] 2017-05-24 07:44
@tulir when would you guys be merging this in Masters.
It would be good to have the production version of OpenAPI Designer with atleast the fixed bugs.
Otherwise, users may become confused with them.

**Comment by tulir** [comment] 2017-05-24 08:08
We can merge `master` into `gh-pages` tomorrow.

**Comment by tulir** [comment] 2017-05-25 09:28
@Nazarah `master` has been merged into `gh-pages`

**Comment by Nazarah** [comment] 2017-05-26 07:40
tested in Masters.
The bug has been fixed.
